CREATE TABLE [dbo].[Test]
(
[Id] [int] NOT NULL IDENTITY(1, 1),
[test_name] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Test] ADD CONSTRAINT [PK__Test__3214EC077F60ED59] PRIMARY KEY CLUSTERED  ([Id]) ON [PRIMARY]
GO
